apiVersion: apps/v1
kind: Deployment
metadata:
  name: rent-app
spec:
  selector:
    matchLabels:
      app: rent-app
  template:
    metadata:
      labels:
        app: rent-app
    spec:
      containers:
      - name: rent-app
        image: rent-app:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "3000"
        - name: DB_HOST
          value: postgresql.default.svc.cluster.local
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_DATABASE
          value: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
